name: Build macOS Executable with PyInstaller

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pyinstaller
        # Add any other packages your script uses:
        python -m pip install soundfile pandas mutagen

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --icon=gate.ico your_script.py
        mkdir packaged
        mv dist/your_script packaged/

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: macOS-executable
        path: packaged/your_script
