name: Build macOS and Windows Executables

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas soundfile mutagen

      - name: Build macOS binary
        run: |
          pyinstaller --onefile GateKeeper.py
          mkdir -p packaged
          mv dist/GateKeeper packaged/GateKeeper_macos

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: GateKeeper_macos
          path: packaged/GateKeeper_macos

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas soundfile mutagen

      - name: Build Windows executable
        run: |
          pyinstaller --onefile GateKeeper.py
          mkdir packaged
          move dist\GateKeeper.exe packaged\GateKeeper.exe

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: GateKeeper
          path: packaged/GateKeeper.exe
