name: Build macOS and Windows Executables

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller soundfile pandas mutagen

      - name: Build macOS app
        run: |
          pyinstaller --onefile GateKeeper.py
          mkdir packaged
          mv dist/your_script packaged/your_script_macos

      - name: Upload macOS binary
        uses: actions/upload-artifact@v3
        with:
          name: your_script_macos
          path: packaged/your_script_macos

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller soundfile pandas mutagen

      - name: Build Windows exe
        run: |
          pyinstaller --onefile GateKeeper.py
          mkdir packaged
          move dist\your_script.exe packaged\your_script_windows.exe

      - name: Upload Windows .exe
        uses: actions/upload-artifact@v3
        with:
          name: your_script_windows
          path: packaged/your_script_windows.exe
