name: Build macOS and Windows Executables

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas soundfile mutagen

      - name: Build macOS binary
        run: |
          pyinstaller --onefile GateKeeper.py
          mkdir -p packaged
          mv dist/your_script packaged/your_script_macos

      - name: Upload macOS binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: your_script_macos
          path: packaged/your_script_macos

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas soundfile mutagen

      - name: Build Windows executable
        run: |
          pyinstaller --onefile GateKeeper.py
          mkdir packaged
          move dist\your_script.exe packaged\your_script_windows.exe

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3.1.3
        with:
          name: your_script_windows
          path: packaged/your_script_windows.exe
